### PR TITLE
Feature/upload documentation

### LINKED ISSUE #938: Design and implement upload documentation functionality to Documentation tab
Api owners must be able to upload a Swagger for an API backend. Alternatively, they can provide a link to external documentation.

# User stories
As an API owner, I want to upload a Swagger document into Apinf so that I can help API consumers understand API structure.
As an API owner, I want to add a link to my existing API documentation so that I can reuse the existing documentation.

# Definition of done

## Design
* [ ] Wireframe for adding/uploading Swagger documentation and providing link.
  * [ ] Revise the wireframe working with the developer.

## Collection
* [ ] Define a schema for storing the documentation. It must contain at least file id and URL fields.
* [ ] Create a publication and subscription.

## UI
* [ ] Create view for uploading the file and adding the link. 
* [ ] Create functionality to delete an uploaded file.
* [ ] Consider how to handle a pre-existing Swagger file if a new file is added.
* [ ] Remove the document upload functionality from the Edit API backend form

## Usability test
* [ ] Conduct a usability test for the working prototype.

### PR DESCRIPTION
**Pull request by jykae**
Closes #938 

## Proposed changes

- add meteor-uploads packages
- documentation tab for uploading Swagger documentation file

@apinf/developers please review

### CODE REVIEW

**Comment by brylie** [comment]
We should consider merging this after the 1.3 upgrade branch, since it depends on changes introduced in that branch.

**Comment by jykae** [comment]
Yep, and I am still working on this, just uploading to filesystem works currently. WIP

**Comment by brylie** [comment]
When running the code, I get the following error:

```
While selecting package versions:
   error: unknown package in top-level dependencies: npm-container
```

**Comment by brylie** [comment]
- Add confirmation on success (e.g. s-alert)
- Confirm with user before deleting file
- Change button label/visibility when no file exists

**Comment by Nazarah** [comment]
Delete confirmation message: "Are you sure you want to delete the file <filename>"?
If no file name, simply keep the image beside the message.
another version: "You are about to delete a file. Are you sure?"
Keep focus on cancel button

**Comment by Nazarah** [comment]
S-alert message: Upload successful. Please check the Swagger UI to get the file URL.

**Comment by philippeluickx** [comment]
Common pattern for progress bar: https://github.com/zhouzhuojie/meteor-nprogress

**Comment by bajiat** [comment]
Combined to PR #967. Closing this PR

**Pull request closed without merging**
