### PR TITLE
Add API usage instructions template include

### LINKED ISSUE #1120: View usage button not working on API Backend page
The *View Usage Instructions* button has stopped working on the *API Backend* page.

# Steps to reproduce
1. view a single API Backend
2. click **View usage instructions**

# Observed results
No UI change is visible.

# Expected results
A UI text should appear indicating how to use the API backend.

### PR DESCRIPTION
**Pull request by brylie**
Closes #1120 

# Changes
- Add API Usage Instructions template to API Backend page header

### CODE REVIEW

**Comment by brylie** [comment]
@philippeluickx what is the status of this PR review? Ping @bajiat.

**Comment by nnn** [comment]
Closes #1157

**Comment by philippeluickx** [comment]
@brylie Sorry for the delay. Couldn't close as we didn't finnish the setup on my dev machine. Feel free to close it.

**Comment by brylie** [comment]
@philippeluickx all good. We also merged a fix to the error you and I encountered:

- https://github.com/apinf/api-umbrella-dashboard/pull/1150

**Comment by philippeluickx** [comment]
Nice!

**Pull request merged**
