### PR TITLE
Feature/api usage ui documentation

### PR DESCRIPTION
**Pull request by brylie**
This pull request improves the usability for API backends by:
* Adding navigation link to API page from Catalogue view
* Displaying help text instructing user how to call API Umbrella

### CODE REVIEW

**Comment by brylie** [comment]
@apinf/developers please review ASAP, as this may be needed by the hackathon participants over the weekend.

**Comment by bajiat** [comment]
@mauriciovieira Can you review the PR? I understood that you have been discussing this with Brylie in IRC.
@elnzv If the code is ok and this is merged, would you be able to deploy it before tomorrow?

**Comment by brylie** [comment]
It is a quick usability fix for people to figure out how to work with a given API backend. The two main pages that have been modified are:
* API Catalogue now has links to individual API Backend pages
* API Backend page now has button (in upper right) that toggles a help box

There are sub-templates for the buttons and help box.

I also had to create a server method to get the API Umbrella base URL, since it is stored in a private setting.

Additional changes include a fix to the linter file.

**Comment by ccsr** [comment]
@mauriciovieira could you please review it and if everything is ok then please indicate to @elnzv so that he can go forward with the deployment

**Comment by mauriciovieira** [comment]
Sounds good! :+1:

**Pull request merged**
