### PR TITLE
Feature/swagger doc select

### PR DESCRIPTION
**Pull request by brylie**
Add Swagger documentation select menu to View Documentation page.

### CODE REVIEW

**Comment by bajiat** [comment]
@mauriciovieira or @elnzv Could either of you review this code? Please comment here if you take the responsibility.

**Comment by bajiat** [comment]
@mauriciovieira @elnzv PR still work in progress, don't review yet.

**Comment by elnzv** [comment]
@brylie, what is the status, is it ready to be reviewed and merged?

**Comment by elnzv** [comment]
Looks good, great job, @brylie!

**Pull request merged**
