### PR TITLE
Add docker-compose.yml for production

### LINKED ISSUE #1227: Docker production setup
Chapter 2 for https://github.com/apinf/api-umbrella-dashboard/issues/650

- Make Docker setup for "production" use.

### PR DESCRIPTION
**Pull request by shaliko**
Closes #1227

* Add docker-compose.yml for production.
* Add Docker-compose instructions.

Requires https://github.com/apinf/api-umbrella-dashboard/issues/1216

### CODE REVIEW

**Comment by jykae** [comment]
Is require fix also some keyword in Github, this PR is linked to API key issue. o_O

**Comment by shaliko** [comment]
@jykae I think 'require' not GitHub keyword, at least I not found information about that ;) I just wanted mark that this feature not really useful until will be fixed issue #1216. User will flow by instructions but will not able create API request.

**Comment by jykae** [comment]
@shaliko But "fix" is keyword to close given issue: https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues I update the PR, so that we are not closing API key issue with this PR.

**Comment by shaliko** [comment]
@jykae OK, got it :)

**Comment by shaliko** [comment]
@jykae Please do not accept that task right after release #1216  I will need build new image https://github.com/apinf/api-umbrella-dashboard/blob/develop/CONTRIBUTING.md#building-images.

**Comment by jykae** [comment]
@shaliko Don't worry we are testing this anyway, and #1216 has still some weirdness on saving Branding object.

**Comment by jykae** [comment]
@apinf/developers I won't be able to review this today before summer vacation. Could someone else review this?

**Comment by brylie** [comment]
@shaliko #1216 has been merged. Should we merge this PR yet?

**Comment by shaliko** [comment]
@brylie Thanks for notice, now I need make new Docker images and update pull request. After that we can merge this request, will notice you soon.

**Comment by shaliko** [comment]
@brylie Updated "apinf/apinf:latest" docker image. We can close that issue.

BTW I will be happy if you will try run docker-compose.yml for production based on instructions.

**Comment by bajiat** [comment]
@nnn Will you try to run docker-compose.yml with instructions?

**Comment by nnn** [comment]
@bajiat, copy.

**Comment by nnn** [comment]
@shaliko, please finish **with docker compose** instructions based on our yesterday discussion.

**Comment by shaliko** [comment]
@nnn Updated.

**Pull request merged**
