### PR TITLE
Feature/fix collection permissions

### LINKED ISSUE #1413: Settings collection is insecure (insert and update)
The Settings collection needs security rules, specifically for the following methods:

- insert
- update

### LINKED ISSUE #1415: FeedbackVotes collection security
The FeedbackVotes collection needs security rules, specifically for the following methods:

- insert
- update
- remove

### LINKED ISSUE #1425: ApiBackendRatings collection security
The ApiBackendRatings collection needs security rules, specifically for the following method:

- insert
- update

Double check all collection security rules, to make sure only authorized users can perform database operations.

Remove this collection, if it is no longer useful.

### LINKED ISSUE #1523: Refactor ApiBackendRatings collection to follow project structure guidelines
The ApiBackendRatings collection does not follow our project structure. Make sure of the following:

- ApiBackendRatings is divided into relevant files
  - index.js
  - schema.js
  - permissions.js
- ApiBackendRatings is defined with export syntax
- ApiBackendRatings is imported into relevant files

### PR DESCRIPTION
**Pull request by brylie**
Closes #1413 
Closes #1415 
Closes #1425 
Closes #1523

# Changes
- make sure `userId` and `document` parameters are passed in to all allow/deny rules
- improve Settings collection security
- improve FeedbackVotes collection security
- improve Ratings collection security
- refactor ApiBackendRatings collection to follow project structure guidelines

### CODE REVIEW

**Comment by brylie** [comment]
@apinf/core please review ASAP.

**Comment by jykae** [comment]
Reviewing

**Comment by jykae** [comment]
@brylie Autoform errors with Feedback form, also after "Submit", feedback not added. Can not merge this yet.

nayttokuva 2016-09-09 kello 12 52 43

**Comment by brylie** [comment]
Those errors are not related to this PR. Please continue.

**Pull request merged**
