### PR TITLE
Feature/595 userprofile enhancement

### PR DESCRIPTION
**Pull request by sebbel**
This PR is still WIP.

There are a few minor bugs as stated in #595.

- If chosing an already existant username, the usernameExists function is overridden and a "Mongo db duplicate key error" is shown to the user.
- Removed the rules in Meteor.user.allow in order to make it work for now. Will re-implement the rules when I know what's going on.

### CODE REVIEW

**Comment by sebbel** [comment]
I would like to remove this Pullrequest in favor of #752

**Comment by brylie** [comment]
OK.

**Comment by brylie** [comment]
@sebbel delete the feature branch, if it is not relevant to your other pull request.

**Comment by sebbel** [comment]
Okay, will delete it now

**Pull request closed without merging**
