### PR TITLE
Feature/eslint

### LINKED ISSUE #1466: Add ESLint configuration to project
In order to enforce basic coding standards, and automatically check low-level details, we can use the ESLint package. Add the ESLint package to our project as a development dependency. Enable basic lint rules for Airbnb, Meteor, and Babel.

### PR DESCRIPTION
**Pull request by brylie**
Closes #1466 

# Changes
- Add ESLint to project dev dependencies
- Add Airbnb base rules
- Add Meteor lint rules
- Add Babel lint rules
- Ignore third party libraries in our sourcecode

### CODE REVIEW

**Comment by nnn** [comment]
@brylie, how can I test it?

**Comment by nnn** [comment]
@brylie, did next:

1. Installed https://github.com/AtomLinter/linter-eslint
2. meteor npm install
3. meteor npm run lint

Getting:
30009 problems (27804 errors, 2205 warnings)

**Comment by brylie** [comment]
@nnn jep. We have a lot of lint. I was able to get the number of errors down to around 5,000 by ignoring third party libraries:

> 5059 problems (4654 errors, 405 warnings)

**Comment by brylie** [comment]
Calling `eslint --fix .` reduces the number of issue by half:

> 2427 problems (2148 errors, 279 warnings)

**Comment by frenchbread** [comment]
Tested. Works as expected! I would only suggest to add one rule: since we used to add `spaces` before function parenthesis, this helps :

### `package.json`
```json
"rules": {
      "space-before-function-paren": ["error", { "anonymous": "always", "named": "always" }]
    }
```

[Source](http://eslint.org/docs/rules/space-before-function-paren)

**Comment by brylie** [comment]
@nnn and/or @frenchbread will this be merged today, or is more work needed?

**Comment by frenchbread** [comment]
Looks good to me. Unless you are still committing here, I'll merge this.

**Comment by brylie** [comment]
Cool. I don't have any more edits.

**Pull request merged**
