### PR TITLE
Feature/ratelimitmerge

### PR DESCRIPTION
**Pull request by JuusoV**
Created field for rate limit.
Also fixed the issue with git conflict.

### CODE REVIEW

**Comment by brylie** [comment]
Is this pull request complete, or are you adding files still @JuusoV?

**Comment by JuusoV** [comment]
@brylie its complete.

**Comment by brylie** [comment]
OK, your commit messages are 'asd' and 'asd2'. Will you please update your commit messages to be more descriptive of the actual changes?

**Comment by brylie** [comment]
There are some [examples of descriptive commit messages](https://github.com/apinf/api-umbrella-dashboard/commits/develop) in our develop branch.

**Comment by brylie** [comment]
@JuusoV your [original pull request](https://github.com/apinf/api-umbrella-dashboard/pull/139) had meaningful commit messages, for the first two commits at least.

**Pull request closed without merging**
