### PR TITLE
Feature/project structure cleanup

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by brylie** [comment]
@apinf/developers please test this PR. Comment here after you have tested, indicating any problems or just general approval.

**Comment by frenchbread** [comment]
Everything worked for me. Regular authentication as well as authentication using github.

**Comment by elnzv** [comment]
Error when submitting contact form:

```console
Exception while invoking method 'sendEmail' ReferenceError: Schema is not defined
I20150804-13:36:59.613(3)?     at [object Object].Meteor.methods.sendEmail (app/server/methods/contactForm.js:4:16)
I20150804-13:36:59.613(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150804-13:36:59.613(3)?     at packages/ddp/livedata_server.js:648:1
I20150804-13:36:59.613(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150804-13:36:59.613(3)?     at packages/ddp/livedata_server.js:647:1
I20150804-13:36:59.613(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150804-13:36:59.613(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150804-13:36:59.613(3)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by elnzv** [comment]
Another error, trying to change profile picture:

```console
Exception in setTimeout callback: RangeError: Maximum call stack size exceeded
    at Object.EJSON.clone (http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:491:24)
    at http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:530:22
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:164:22)
    at Object.EJSON.clone (http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:529:5)
    at http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:530:22
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:164:22)
    at Object.EJSON.clone (http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:529:5)
    at http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:530:22
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:164:22)
    at Object.EJSON.clone (http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:529:5)
```

**Comment by JuusoV** [comment]
Nothing broke for me.

**Comment by elnzv** [comment]
Change password form (/account) doesn't work.
Nothing happens when I click "Change Password" button. No messages in both consoles.

**Pull request merged**
