### PR TITLE
Feature/798 swagger viewer error check, closes #798

### LINKED ISSUE #798: Uncaught exception from Swagger viewer in APIKA
* Uncaught exception from Swagger viewer in apika.digipalvelutehdas.fi 
swagger-viewer

Exception comes from "both/collections/apiDocs.js" 
Maybe data context issue as we are using "this" quite confidently.

Definition of done
---
* [ ] Error handling exists in both/collections/apiDocs.js
* [ ] The existence of Meteor.User is checked by error handling

### PR DESCRIPTION
**Pull request by jykae**

### CODE REVIEW

**Comment by jykae** [comment]
I suppose this closes #841 as well, if it works.

**Comment by jykae** [comment]
Traced the error with @brylie Now able to produce error locally as well. Problem is with the data context. We have subscribed to ApiDocs, but not to ApiBackends user does not have rights to manage.

**Comment by jykae** [comment]
@apinf/developers please review

**Comment by frenchbread** [comment]
Tested, work good :+1:

**Pull request merged**
