### PR TITLE
Meteor update

### LINKED ISSUE #1318: Update Meteor to the latest version
Meteor 1.3.5.1 was recently released.
Update project to latest Meteor version,  update dependencies and test.

### LINKED ISSUE #1351: Replace collection FS with meteor-file-collection
The FS collection has been deprecated. Since it is still used for logo and other image upload, we need to implement similar logic as we using for uploading documentation.

### PR DESCRIPTION
**Pull request by nnn**
Closes #1318 
Closes #1351 

Updated to v1.4.0.1
Please test and merge.

Release notes - https://github.com/meteor/meteor/blob/devel/History.md

### CODE REVIEW

**Comment by nnn** [comment]
WIP. getting this error:

```

While minifying app stylesheet:
packages/minifier-css/minifier.js:184:1: Cannot call method 'replace' of null
  at toOSPath (packages/minifier-css/minifier.js:184:1)
  at pathRelative (packages/minifier-css/minifier.js:205:1)
  at packages/minifier-css/minifier.js:164:1
  at Array.forEach (native)
  at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
  at packages/minifier-css/minifier.js:122:1
  at Array.forEach (native)
  at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
  at rewriteRules (packages/minifier-css/minifier.js:99:1)
  at Object.CssTools.rewriteCssUrls (packages/minifier-css/minifier.js:85:1)
  at packages/minifier-css/minifier.js:55:1
  at Array.forEach (native)
  at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
  at Object.CssTools.mergeCssAsts (packages/minifier-css/minifier.js:32:1)
  at packages/minifyStdCSS/plugin/minify-css.js:79:1
  at CssToolsMinifier.processFilesForBundle (packages/minifyStdCSS/plugin/minify-css.js:17:1)
```

Created an issue - https://github.com/meteor/meteor/issues/7446

**Comment by philippeluickx** [comment]
Getting the next issue:

[[[[[ ~/Development/projects/sampo/apinf/api-umbrella-dashboard ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
I20160729-12:25:23.939(3)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20160729-12:25:24.189(3)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
I20160729-12:25:27.940(3) (synced-cron-server.js:63) SyncedCron: Scheduled "Sync API Umbrella Users and API Backends" next run @Fri Jul 29 2016 12:25:27 GMT+0300 (EEST)
=> Started your app.

=> App running at: http://localhost:3000/

**Comment by philippeluickx** [comment]
Issue is linked to deprecated cfs package, see discussion: https://forums.meteor.com/t/deprecating-collectionfs/16921/2

Migrating to https://github.com/vsivsi/meteor-file-collection to avoid future problems.

**Comment by nnn** [comment]
@philippeluickx, removing cfs and everything related to it didn't help.

**Comment by philippeluickx** [comment]
@nnn Some other package then? Try to remove all packages and add them back in one by one...?

**Comment by nnn** [comment]
@philippeluickx, it would be great if you can help with it :smile:

**Comment by philippeluickx** [comment]
Working on it

**Comment by philippeluickx** [comment]
Linked to old cfs packages.
See https://github.com/CollectionFS/Meteor-CollectionFS/pull/984

I propose that we get rid of all the "old" file-related packages and refactor code to use 1, well-maintained library - https://github.com/vsivsi/meteor-file-collection
Open backlog issue: https://github.com/apinf/api-umbrella-dashboard/issues/1351

I branched out with a removed cfs and comment out code where this was still used. Everything runs now on my machine - https://github.com/apinf/api-umbrella-dashboard/tree/meteor-update-removed-cfs
I did follow https://guide.meteor.com/1.4-migration.html#binary-packages-require-build-toolchain and ran
`meteor npm rebuild`
So this _might_ also be necessary

**Comment by philippeluickx** [comment]
Hooray!

**Comment by philippeluickx** [comment]
There is a short moment where we get the "broken image link" icon when uploading a new picture on http://localhost:3000/branding

**Comment by nnn** [comment]
@brylie, please review.

**Comment by brylie** [comment]
I just ran meteor update once more. There were about 5 additional updates.

**Comment by brylie** [comment]
When visiting the landing page, I get the following error:

```js
Exception in template helper: TypeError: Cannot read property 'projectLogoFileId' of undefined
    at Object.projectLogoExists
```

**Comment by brylie** [comment]
We may need a try/catch around the code that uses `projectLogoFileId`, or to pre-verify that the branding object is not `undefined` before using one of its properties.

**Comment by brylie** [comment]
It seems like there is a bug in the `projectLogoExists` template helper. It is throwing the above error even when I have uploaded a project logo.

**Pull request merged**
