### PR TITLE
Feature/meteor 1.3 update

### LINKED ISSUE #935: Meteor update
Create a branch, run the Meteor update on Meteor core and all packages. Deprecate unused to packages.

### LINKED ISSUE #939: API Backend Feedback form not submitting (after 1.3 upgrade)
While working on the Meteor 1.3.x upgrade, the API Backend Feedback form does not appear to be working.

Steps to reproduce:
1. Add an API backend
2. View the API backend page
3. Click the "Feedback" tab
4. Click "Add Feedback"
5. Fill in, and submit the form

# Related
Issue #935 - update Meteor

### LINKED ISSUE #940: ReferenceError: ss is not defined
During the Meteor 1.3 upgrade process (Issue #955), the following error is visible in the browser console:

```js
ReferenceError: ss is not defined
```

### LINKED ISSUE #941: Export API Backend: ReferenceError: jsyaml is not defined
During the Meteor 1.3 upgrade (issue #935), the following error is visible in the console:

```
ReferenceError: jsyaml is not defined
```

Steps to reproduce
1. visit an API Backend
2. click the 'Export' tab
3. click the 'YAML' button

### LINKED ISSUE #942: API Catalog: rating stars widget not available
During the Meteor 1.3 upgrade (issue #935), the rating widget in the API Catalog table does not appear.

The following traceback appears in the browser console:

```
ReferenceError: ss is not defined meteor.js:930:11
getRating@http://localhost:3000/app/app.js?hash=8469f16ab5f7fc1b6e446c435bbaf166fa1e3c61:36579:13
require<.client.views.catalogue.rating["rating.js"]/Template.apiBackendRating.rendered/<@http://localhost:3000/app/app.js?hash=8469f16ab5f7fc1b6e446c435bbaf166fa1e3c61:5497:49
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1875:18
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1873:14
Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2214:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1872:12
Tracker.Computation.prototype._compute@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:351:5
Tracker.Computation.prototype._recompute@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:370:9
Tracker._runFlush@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:509:9
onGlobalMessage@http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:401:11
 meteor.js:930:11
```

### LINKED ISSUE #949: Resolve Elastic-REST error after Meteor 1.3 upgrade
> TypeError: Object [object Object] has no method 'npmRequire'
>    at new ElasticRest (packages/frenchbread_elastic-rest/server/elastic-rest.js

OK, our NPM dependency handling has changed, so we probably need to use the ES2015 import syntax in that file.

Suggestion: while solving this, add the package under Apinf organization.

Co-pilot: @brylie

### PR DESCRIPTION
**Pull request by brylie**
Closes #935 
Closes #939 
Closes #940
Closes #941
Closes #942
Closes #949

# Suggested changes
- Update all possible project dependencies, including Meteor
- add package.json for NPM dependency management
- remove unneeded packages
  - switch NPM package handling

### CODE REVIEW

**Comment by brylie** [comment]
@frenchbread, @elnzv, and @jykae will you all please test this PR?

@frenchbread pay particular attention to the dashboard, such as the getChartData method. I have moved the elasticsearch dependency to package.json, and removed the `meteorhacks:npm` wrapper package.

**Comment by elnzv** [comment]
Getting this in server console on _/dashboard_ 

```
 Exception while invoking method 'getChartData' TypeError: Object [object Object] has no method 'npmRequire'
     at new ElasticRest (packages/frenchbread_elastic-rest/server/elastic-rest.js:33:1)
     at [object Object].getChartData (server/methods/elasticSearch.js:48:16)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
     at packages/ddp-server/livedata_server.js:711:19
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at packages/ddp-server/livedata_server.js:709:40
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at packages/ddp-server/livedata_server.js:707:46
```

**Comment by brylie** [comment]
> TypeError: Object [object Object] has no method 'npmRequire'

OK, our NPM dependency handling has changed, so we probably need to use the ES2015 import syntax in that file.

**Comment by jykae** [comment]
Could we bring elastic-rest under Apinf organization if not there already? just a side note..

**Comment by jykae** [comment]
@brylie Got yesterday's Github exception removed by commenting out https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/accounts.js#L60 onLogin handler. From history it looks like this might be some legacy code, was still able to login with Github. Consider cleaning up.

**Comment by brylie** [comment]
Good catch @jykae

**Comment by brylie** [comment]
We need to deprecate meteorhacks:npm from any project dependencies. @frenchbread will you see if you can update the elastic-rest module, so that it uses NPM directly?

**Comment by frenchbread** [comment]
@brylie Yep. Had that idea in mind. Will do.

**Comment by brylie** [comment]
@frenchbread we are currently refactoring the dashboard code. I will push it to this branch right now.

**Comment by brylie** [comment]
@frenchbread we have refactored the `getChartData` server method, which is working as of now. The last part that is giving us trouble, is getting the data into the charts, from within the method callback. Please review, and fix if possible, the `client/views/dashboard/charts/charts.js`

**Comment by jykae** [comment]
@brylie @frenchbread 
Notes from the evening coder: I think it works now, we just forgot to return the promise result. Added dc from npm

**Comment by elnzv** [comment]
Getting this error on startup:

```
=> Errors prevented startup:

   While selecting package versions:
   error: unknown package in top-level dependencies: npm-container

=> Your application has errors. Waiting for file change.
```

If I remove this package manually it will work correctly.
Should I commit those changes and push it in [this](feature/meteor-1.3-update) branch?

**Comment by frenchbread** [comment]
Working on #972 #949 since they are blocking this one

**Comment by brylie** [comment]
@frenchbread please see my comment in #949

**Pull request merged**
