### PR TITLE
Hotfix/hosts status check - closes #529

### LINKED ISSUE #529: Remove hardcoded urls for Apinf's services status checking

### PR DESCRIPTION
**Pull request by frenchbread**
@mauriciovieira or @elnzv Please review this hotfix. I removed hard-coded urls for status checking. Please also refer to updated README.md file, now need to provide hosts for apinf as https://apinf.io and apiUmbrella as https://umbrella.apinf.io as separate fields.

### CODE REVIEW

**Comment by mauriciovieira** [comment]
@frenchbread It is pretty common to version a _,some_dotfile.example_ in the repository of rails projects. I think we can leave a _settings.json.example_ in the repository along with the README instructions. Would you like to do this?

**Comment by elnzv** [comment]
@mauriciovieira, agree with you about _settings.json.example_ file, but I think that is not a part of current PR.

**Comment by frenchbread** [comment]
@mauriciovieira Like this idea. Gonna create a new issue for that. Do you think it is better to provide real paths like https://apinf.io and others for elasticsearch and apiUmbrella, or just leave them as https://example.com ?

**Comment by mauriciovieira** [comment]
@frenchbread just like it is written in the README ;-)

**Pull request merged**
