### PR TITLE
Fix empty API key for first user

### LINKED ISSUE #1216: Empty API key right after registration first user
First user get empty API key because API-Umbrella settings does not available when APInf try create user and get API key.

How to reproduce:

1) Make new installation of api-umbrella-dashboard without settings.json
2) Register first user and fill data in wizard.
3) Visit https://apiumbrellahost/profile

https___apinf_usubov_com_profile

Possible fix move "create user and get API key after user have done setup wizard".

### PR DESCRIPTION
**Pull request by jykae**
Closes #1216 

## Proposed changes
- change routing to show setup wizard as the first thing, onSuccess route first user to signUp
- change allow/deny rules for Branding, ProjectLogo & CoverPhoto (fixes Branding not saved issue)

@apinf/developers please review

### CODE REVIEW

**Comment by brylie** [comment]
The branding problem might be related to collection allow/deny rules. E.g. the Branding collection probably only allows administrator users to insert/update.

**Comment by jykae** [comment]
@brylie Oh, good note, thanks. I'll check..

**Comment by jykae** [comment]
Fixed issue with permissive allow/deny rules.

@brylie Checking "admin" role is good though, do you know if we can update allow rules for collection after setup wizard so after that it would allow only admins to manipulate Branding & Settings?

**Comment by jykae** [comment]
Based on discussion after daily, I make new PR with with existing flow + add "Get Umbrella API key" button to "User profile" page to get key if it doesn't exist. This way we can keep database rules for Branding & Settings collections to allow only admin to insert/update for better security.

**Comment by jykae** [comment]
@brylie This PR can be closed without merging, when new solution #1247 is accepted.

**Pull request closed without merging**
