### PR TITLE
Feature/api backend ratings. Closes #519

### LINKED ISSUE #519: Implement API Rating field and widget
# Feature
Create a rating feature for API Backends. Users can select a rating, and aggregate ratings are displayed on the API Backend page and API Backends catalog.

# Design
Rating design

# Resources
* [jQuery Rate It package](https://atmospherejs.com/dandv/jquery-rateit)

# Related
Related to #471

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by brylie** [comment]
Removing WIP label after recent additions.

**Comment by frenchbread** [comment]
@brylie Code looks good. But while testing found out that when "current user" rates an API, the counter with icon disappears. Is that supposed to be like that?

screen shot 2015-11-06 at 10 39 25

**Comment by brylie** [comment]
@frenchbread status update?

**Comment by frenchbread** [comment]
@bajiat Good job! Merging..

**Comment by frenchbread** [comment]
@brylie Good job! Merging..

**Pull request merged**
