### PR TITLE
Set username from Github; cleanup; comments. Closes #64

### LINKED ISSUE #64: Get profile name when authenticating users via Github
When authenticating users via Github, an object is returned with basic user details (email, etc). Get the user name (real name or otherwise) from the authentication object, and store it in our user profile. 

There is a [support request](https://github.com/Jabbslad/accounts-github/issues/5) with the upstream package relevant to this feature.

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by brylie** [comment]
@apinf/developers please review

**Comment by brylie** [comment]
This is related to @sebbel's work with required usernames (issue #595).

**Comment by bajiat** [comment]
@frenchbread or @jykae Are you available for reviewing this PR?

**Comment by frenchbread** [comment]
Reviewing this one..

**Comment by frenchbread** [comment]
Tested. Works as expected!

**Pull request merged**
