### PR TITLE
Add Docker configuration

### LINKED ISSUE #650: Create docker installation file
As part of our packaging process, we would like to support Docker. Create a basic Dockerfile for the Apinf installer.

# Definition of done
* [ ] System administrators can deploy an Apinf + API Umbrella stack in one command, via Docker
* [ ] Developers can set up a local development environment in one command, using Docker, sh, or something similar
* [ ] **Bonus**: System administrators can deploy Apinf + API Umbrella using [Rancher](http://rancher.com/rancher/) UI

# Related
- There is an open [pull request](https://github.com/apinf/api-umbrella-dashboard/pull/900) with initial work on an Apinf Docker image
- We opened an [upstream issue](https://github.com/NREL/api-umbrella/issues/228) requesting that NREL provide an up-to-date Docker image for API Umbrella.

### PR DESCRIPTION
**Pull request by shaliko**
Closes #650 

Add Docker configuration for 
* Production deploy https://hub.docker.com/r/apinf/apinf/
* Setup development environment

### CODE REVIEW

**Comment by brylie** [comment]
The instructions do not mention installing `docker-compose`.

**Comment by brylie** [comment]
Please include step-by-step instructions, including setting up related images:

``` 
mongo uses an image, skipping
apiumbrella uses an image, skipping
```

**Comment by brylie** [comment]
I get the following error on step 3 (`docker-compose up`):

```
Cannot link to a non running container: /apiumbrelladashboard_apiumbrella_1 AS /apiumbrelladashboard_web_1/apiumbrella
```

**Comment by brylie** [comment]
I also get the following error when trying to add the docker IP to my hosts file:

```
docker-machine: command not found
```

**Comment by shaliko** [comment]
@brylie ```Cannot link to a non running container```

Can you try run 
```
docker-compose up web
```

**Comment by brylie** [comment]
```
$ docker-compose up web
apiumbrelladashboard_mongo_1 is up-to-date
Starting apiumbrelladashboard_apiumbrella_1
Starting apiumbrelladashboard_web_1
ERROR: Cannot link to a non running container: /apiumbrelladashboard_apiumbrella_1 AS /apiumbrelladashboard_web_1/apiumbrella
```

**Comment by shaliko** [comment]
@brylie And please try this one:

```
docker-compose up apiumbrella
```

**Comment by brylie** [comment]
```
docker-compose up apiumbrella
Starting apiumbrelladashboard_apiumbrella_1
Attaching to apiumbrelladashboard_apiumbrella_1
apiumbrella_1 | luajit: 14:11: did not find expected '-' indicator
apiumbrella_1 | stack traceback:
apiumbrella_1 | 	[C]: in function 'error'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:287: in function 'error'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:306: in function 'parse'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:412: in function 'load_node'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:364: in function 'load_node'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:349: in function 'load_node'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:349: in function 'load_node'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:349: in function 'load_node'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:349: in function 'load_node'
apiumbrella_1 | 	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:466: in function 'load'
apiumbrella_1 | 	...d/apps/core/current/src/api-umbrella/cli/read_config.lua:155: in function 'read_system_config'
apiumbrella_1 | 	...d/apps/core/current/src/api-umbrella/cli/read_config.lua:369: in function 'read_config'
apiumbrella_1 | 	...mbedded/apps/core/current/src/api-umbrella/cli/setup.lua:296: in function 'setup'
apiumbrella_1 | 	.../embedded/apps/core/current/src/api-umbrella/cli/run.lua:39: in function 'run'
apiumbrella_1 | 	...ella/embedded/apps/core/current/src/api-umbrella/cli.lua:8: in function 'command_function'
apiumbrella_1 | 	...ella/embedded/apps/core/current/src/api-umbrella/cli.lua:130: in function 'cli'
apiumbrella_1 | 	...umbrella/embedded/apps/core/current/bin/api-umbrella-cli:28: in main chunk
apiumbrella_1 | 	[C]: at 0x00404720
apiumbrelladashboard_apiumbrella_1 exited with code 1
```

**Comment by Alapan** [comment]
Can Docker be installed on a 32-bit machine? My Ubuntu machine is 32-bit, not 64. I also couldn't open [this link](https://docs.docker.com/engine/installation/ubuntulinux/) given [here for Linux](https://github.com/apinf/api-umbrella-dashboard/blob/issue-650-create-dockerfile/CONTRIBUTING.md#development-installation-with-docker).

**Comment by shaliko** [comment]
@Alapan I not tried 32-bit, but based on google answer, should works.

Try use this link https://docs.docker.com/engine/installation/linux/ubuntulinux/, in "Development installation with Docker" typo, I will fix it.

**Comment by shaliko** [comment]
@Alapan from docker docs:

```
Prerequisites
Docker requires a 64-bit installation regardless of your Ubuntu version. Additionally, your kernel must be 3.10 at minimum. The latest 3.10 minor version or a newer maintained version are also acceptable.
```

So now I am not sure that it will work for you.

**Comment by Alapan** [comment]
@shaliko No, in that case, this task cannot be performed on my machine. Some other 64-bit Ubuntu machine will be needed.

**Comment by jykae** [comment]
@shaliko Tested "docker-compose up" (development env)
Works great on Macbook Pro 64-bit using docker-toolbox :) 

We might want to align MongoDB with Meteor bundled mongo version (currently 2.6.7) MongoDB driver upgrade for 3.2 is on roadmap for MDG.

Did you have docker-compose.yml for production env? I think we could release to Docker Hub and pull image from there when installing to production.

**Comment by shaliko** [comment]
@jykae We already pushed image to docker hub https://hub.docker.com/r/apinf/apinf/ and provided instructions for run it.

1) Good point about MongoDB, should we provide details about mongo driver version in Readme?
2) I don't have docker-compose.yml for production not sure that we need it. Because looks like docker-compose.yml not fit good for production. What we need is just independently run 2 docker images and then visit apinf-umbrella-dashboard and configure (link to api-umbrella) on settings page in admin UI.

**Comment by shaliko** [comment]
@brylie You still have issue on Linux?

**Comment by elnzv** [comment]
@shaliko, tested on Ubuntu 16.04, it works.

**Comment by shaliko** [comment]
@elnzv Great to hear that, thanks a lot!

**Comment by brylie** [comment]
@shaliko please resolve conflicts, so that we can merge.

**Pull request merged**
