### PR TITLE
Feature/730 latest apibackends frontpage, closes #730

### LINKED ISSUE #730: Add 'Latest API Backends' view to front page
Add the Latest API Backends template to the front page. 

See the picture for wireframe:
ux2

Related issue: #629 

Definition of done
---
* [x] Landing page template includes the latest API backends template (refer to #687).
* [x] Latest API backends responsively adjusts to screen width.
* [x] Latest API backends display  in a grid of boxes.
* [x] Latest API backends template accepts parameter for number of backends shown.

### PR DESCRIPTION
**Pull request by jykae**

### CODE REVIEW

**Comment by jykae** [comment]
@apinf/developers please review. 
@brylie Here are now the internalization fixes you wanted.
Some conflicts seem to exist with the develop branch.

**Comment by jykae** [comment]
@apinf/developers please review, fixed conflict.

**Comment by bajiat** [comment]
@frenchbread Could you kindly review this PR? Brylie has done pair programming on the issue and you would be in good position to review it, since you developed the original code.

**Comment by frenchbread** [comment]
PR looks & works good!
I've also removed the old (temporary) route `latestApiBackends` that is no longer needed.

Please confirm the last commit & feel free to merge :)
@bajiat @jykae @brylie

**Comment by brylie** [comment]
@elnzv please review. :shipit:

**Comment by elnzv** [comment]
Looks good, merging.

**Pull request merged**
