### PR TITLE
Allow navigation from Add API Backend wizard header, closes #803

### LINKED ISSUE #803: Allow navigation from Add API Backend wizard header
The Add API Backend wizard shows the steps in the header area of the template. Currently, the steps do not allow users to navigate backwards when clicking. Adding backward navigation capabilities to the steps in the header may improve usability.

navigation wizard steps

### PR DESCRIPTION
**Pull request by jykae**
Link doesn't work as expected. WIP

### CODE REVIEW

**Comment by jykae** [comment]
Verified, fixes the issue.

**Comment by jykae** [comment]
@brylie First step has to be entered twice. Otherwise it works. Steps have now routes. Could you look at this? Or we could have pair programming session as well.

**Comment by brylie** [comment]
I have opened a [support request](https://github.com/forwarder/meteor-wizard/issues/73) to figure out how to get the `pathFor` helper to work in our sidebar.

**Comment by jykae** [comment]
@brylie Cool, just verified that the first step works now after adding the missing question mark.
Ready for merge?

**Comment by jykae** [comment]
Discussed, so merging.

**Pull request merged**
