### PR TITLE
Hotfix/api logo error

### LINKED ISSUE #1366: API logo upload error
### Steps

1. Upload API logo
2. Upload API Documentation 

### Error

API logo is undefined, can't delete it.

### PR DESCRIPTION
**Pull request by nnn**
Closes #1366 

@apinf/developers, please review.
Test by uploading documentation and logo files.

### CODE REVIEW

**Comment by jykae** [comment]
@nnn Reviewing

**Comment by jykae** [comment]
Adding & Deleting of API logo & documentation seems to work fine.
However API logo is not visible in catalogue :(

nayttokuva 2016-08-09 kello 14 37 20

**Comment by jykae** [comment]
@nnn I am trying to look in the issue..

**Comment by nnn** [comment]
@jykae, thanks, really appreciate it!

**Comment by jykae** [comment]
@nnn Used API backend from template instance data & used that for finding right API backend in template helper. Could you test it @nnn ? I think we can merge this then.

**Comment by nnn** [comment]
@jykae, tested, thanks for the fix.

**Pull request merged**
