### PR TITLE
Enhanced project view; removed AdminLTE

### LINKED ISSUE #1209: Enhance Apinf side menu
Enhance both Apinf side menu aesthetics and functionality

# Potential enhancements
- Selected item should be more visible
- Removing submenu items and making them first level items
- Reordering the menu
- Is it possible to collapse only menu and not Apinf logo?
- Totally collapsible menu?

Related issue: #1211

# Wireframes

* General View

topbar

* Hovered state and dropdown

topbardropdown

* When accessing a particular menu (e.g. catalog)

topbarcataloguview

### LINKED ISSUE #1211: Enhance Apinf top bar
Enhance the aesthetics and functionality of top bar

# Potential enhancements
- Optionally, Add API backend option to top menu
- Make sure Apinf logo is never collapsed
- Remove the hamburger icon related to collapsing side menu from top bar
- Include the language switch for all views (not just landing page)

Related issue: # 1209

### PR DESCRIPTION
**Pull request by nnn**
Closes #1209 
Closes #1211 

# Proposed changes:
- Removed AdminLTE and all related code and functionality
- Removed Sidebar
- Moved all links to navbar
- ...

### CODE REVIEW

**Comment by nnn** [comment]
@apinf/developers, @apinf/design, please review.

**Comment by jykae** [comment]
Overall, I think colors could be a bit softer for eye.
Maybe we could find something help from Google: https://www.google.fi/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=design+color+schemes

For example:
nayttokuva 2016-07-01 kello 11 52 19

Bright light blue on white background is not good combination,
nayttokuva 2016-07-01 kello 11 54 32

Search button style not same size with search box, maybe it could be also different color.
Same thing everywhere where search box is appearing.

nayttokuva 2016-07-01 kello 11 30 45

Last but not least:
Not related on this PR, but our search page was reactive previously, now it works from top navigation and from front page, but search page itself adds empty query string. It seems to broken in nightly as well.. Is there issue raised already?

**Comment by nnn** [comment]
I agree on color schema.
We can make it better. But let's create a separate task for it.
For now I have changed it based on your feedback.

I have tested it in Firefox, Chrome, Edge, IE on Windows 10, search button looks good.
I think it's Safari bug, will try to fix it anyway.

Since search page reactivity bug already exists in the develop, let's resolve it in the separate issue.

**Comment by jykae** [comment]
Mobile view, search box jumps on another row, what you think of it?
nayttokuva 2016-07-01 kello 12 54 11

**Comment by jykae** [comment]
@nnn I merge this, let's do further design improvements on other tasks.

**Comment by brylie** [comment]
A quick note about color contrast is to aim for WCAG AA rating at the least, AAA if possible:
http://webaim.org/resources/contrastchecker/

**Pull request merged**
