### PR TITLE
Feature/meteor update

### LINKED ISSUE #1161: Upgrade packages, including Meteor 1.3.4
As part of our sprint process, we should keep our dependencies up to date. Run `meteor update` and test as a team to make sure things went well.

### PR DESCRIPTION
**Pull request by brylie**
Closes #1161 

# Changes
- upgrade all project dependencies
- upgrade to Meteor 1.3.3
- move Clipboard dependency to npm

### CODE REVIEW

**Comment by nnn** [comment]
While testing this branch, I have found:

/profile:
- apiKey is missing

**Comment by brylie** [comment]
I have updated all packages again, including Meteor 1.3.4. @apinf/core please review.

**Comment by brylie** [comment]
The missing api key is related to an open bug report:
https://github.com/apinf/api-umbrella-dashboard/issues/1216

It was not introduced as part of this upgrade.

**Comment by nnn** [comment]
@brylie, reviewing this.

**Comment by nnn** [comment]
Getting on Windows 10:

```
=> Errors prevented startup:

   While building for web.browser:
   apis/collection/backend.js:1:83: Unexpected token (1:83)

**Comment by nnn** [comment]
@philippeluickx, tested myself, everything works as expected. Test yourself and merge it.

**Comment by philippeluickx** [comment]
Catalog is empty for me, @nnn looking into it.

**Comment by philippeluickx** [comment]
Still empty...

**Comment by philippeluickx** [comment]
I20160628-17:57:08.005(3) (synced-cron-server.js:63) SyncedCron: Exception "Sync API Umbrella Users and API Backends" ReferenceError: ApiBackends is not defined
    at apis/server/methods/apiUmbrella.js:12:34
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at [object Object].syncApiBackends (apis/server/methods/apiUmbrella.js:10:9)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:1617:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Server.apply (packages/ddp-server/livedata_server.js:1616:45)
    at Server.call (packages/ddp-server/livedata_server.js:1559:17)
    at Object.job (server/startup.js:18:16)
    at packages/percolate_synced-cron/synced-cron-server.js:218:1

**Pull request merged**
